# SPDX-FileCopyrightText: 2026 Tom Bamford <tom@bamford.io>
# SPDX-License-Identifier: GPL-2.0-only OR GPL-3.0-only OR LicenseRef-KDE-Accepted-GPL

# The stock plasma-nm this module plugs into.
#
# plasma-nm installs libplasmanm_editor.so and none of its headers. It gives
# the library no SOVERSION, exports no ABI tag and ships no pkg-config file, so
# an installed plasma-nm says nothing about which ABI it is and a mismatch
# would be found by a crash in the connection editor. Two things stand in for
# the versioning upstream does not do, and both are checked here:
#
#   * the headers come from one pinned upstream revision and are digest
#     verified, so the declarations really are that version's;
#   * the installed plasma-nm's version must equal that revision's, which the
#     distribution's package database is asked for.
#
# Symbol-level drift is caught separately and for free: everything linked
# against the host library is linked with -Wl,--no-undefined, so a renamed or
# resignatured function is a failed build rather than a failed dlopen.
#
# Defines the imported target PlasmaNm::Editor.

include(GenerateExportHeader)
include(${CMAKE_CURRENT_LIST_DIR}/PlasmaNmSource.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/PlasmaNmVersion.cmake)

set(PLASMA_NM_PIN_FILE "${PROJECT_SOURCE_DIR}/provenance/plasma-nm-6.7.5.pin"
    CACHE FILEPATH "Pin file naming the plasma-nm revision the private headers come from")
set(PLASMA_NM_DIGEST_FILE "${PROJECT_SOURCE_DIR}/provenance/plasma-nm-6.7.5.sha256"
    CACHE FILEPATH "SHA-256 digests of the pinned plasma-nm headers")
set(PLASMA_NM_SOURCE_DIR "" CACHE PATH
    "plasma-nm source tree matching the pin; scripts/fetch-plasma-nm-source.sh writes one")
set(PLASMA_NM_HOST_VERSION "" CACHE STRING
    "Installed plasma-nm version, when the distribution's package database cannot be asked")
option(PLASMA_NM_ALLOW_ABI_MISMATCH
    "Build even though the installed plasma-nm's version is unknown or differs from the pin" OFF)

plasma_nm_read_pin("${PLASMA_NM_PIN_FILE}" PLASMA_NM_PIN)
message(STATUS "Pinned plasma-nm: ${PLASMA_NM_PIN_VERSION} (${PLASMA_NM_PIN_COMMIT})")

# --- the headers ------------------------------------------------------------

set(_plasma_nm_source "${PLASMA_NM_SOURCE_DIR}")
if(_plasma_nm_source STREQUAL "")
    # Where fetch-plasma-nm-source.sh puts it by default, so a plain
    # fetch-then-configure needs no -D.
    foreach(candidate "${PROJECT_SOURCE_DIR}/plasma-nm-source" "${PROJECT_BINARY_DIR}/plasma-nm-source")
        plasma_nm_source_version("${candidate}" _candidate_version)
        if(NOT _candidate_version STREQUAL "")
            set(_plasma_nm_source "${candidate}")
            break()
        endif()
    endforeach()
endif()
if(_plasma_nm_source STREQUAL "")
    message(FATAL_ERROR
        "No plasma-nm source tree found.\n"
        "This module needs four headers that plasma-nm does not install. Run\n"
        "    scripts/fetch-plasma-nm-source.sh\n"
        "to fetch the pinned revision (${PLASMA_NM_PIN_VERSION}, ${PLASMA_NM_PIN_COMMIT}) into\n"
        "${PROJECT_SOURCE_DIR}/plasma-nm-source, or point -DPLASMA_NM_SOURCE_DIR= at a\n"
        "plasma-nm ${PLASMA_NM_PIN_VERSION} checkout you already have.")
endif()

plasma_nm_verify_source("${_plasma_nm_source}" "${PLASMA_NM_DIGEST_FILE}" "${PLASMA_NM_PIN_VERSION}"
                        _plasma_nm_source_ok _plasma_nm_source_message)
if(NOT _plasma_nm_source_ok)
    message(FATAL_ERROR
        "The plasma-nm source tree does not match the pin: ${_plasma_nm_source_message}\n"
        "Pinned revision: ${PLASMA_NM_PIN_COMMIT} (${PLASMA_NM_PIN_REPOSITORY})\n"
        "Nothing is built against unverified declarations of a library with no versioned ABI.")
endif()
message(STATUS "plasma-nm headers: ${_plasma_nm_source} (${_plasma_nm_source_message})")

# The headers include each other by bare name -- plasma-nm puts both
# libs/editor and libs/editor/widgets on the include path -- so one flat
# directory of copies is what they expect to be compiled in.
set(_plasma_nm_include "${PROJECT_BINARY_DIR}/plasma-nm-host-include")
file(MAKE_DIRECTORY "${_plasma_nm_include}")
file(STRINGS "${PLASMA_NM_DIGEST_FILE}" _plasma_nm_digest_lines)
set(PLASMA_NM_HOST_HEADERS "")
foreach(line IN LISTS _plasma_nm_digest_lines)
    if(line MATCHES "^[0-9a-f]+[ \t]+[*]?(.+)$")
        get_filename_component(_header_name "${CMAKE_MATCH_1}" NAME)
        configure_file("${_plasma_nm_source}/${CMAKE_MATCH_1}" "${_plasma_nm_include}/${_header_name}" COPYONLY)
        list(APPEND PLASMA_NM_HOST_HEADERS "${_header_name}")
    endif()
endforeach()

# plasmanm_editor_export.h is generated by plasma-nm's own build, so there is
# no file to pin; CMake's generator writes the same thing for the consuming
# side that it writes for upstream.
add_library(plasma_nm_export_header_stub OBJECT EXCLUDE_FROM_ALL "${CMAKE_CURRENT_LIST_DIR}/plasmanmexportstub.cpp")
generate_export_header(plasma_nm_export_header_stub
    BASE_NAME plasmanm_editor
    EXPORT_FILE_NAME "${_plasma_nm_include}/plasmanm_editor_export.h")

# --- the installed library --------------------------------------------------

find_library(PLASMA_NM_EDITOR_LIBRARY NAMES plasmanm_editor
    DOC "libplasmanm_editor.so from the installed plasma-nm")
if(NOT PLASMA_NM_EDITOR_LIBRARY)
    message(FATAL_ERROR
        "libplasmanm_editor.so was not found. Install the distribution's plasma-nm "
        "(Arch: plasma-nm, Debian/Ubuntu: plasma-nm, Fedora: plasma-nm) or set "
        "-DPLASMA_NM_EDITOR_LIBRARY= to its path.")
endif()
message(STATUS "plasma-nm editor library: ${PLASMA_NM_EDITOR_LIBRARY}")

# The version of the package that owns that file, asked of whichever package
# manager is present. Owner-based rather than by package name, so a library
# from somewhere else is reported as unknown instead of being matched against
# an unrelated package of a plausible name.
#
# The raw package version is what comes back; turning it into an upstream
# release is plasma_nm_upstream_version()'s job, and it refuses to turn a
# prerelease or a snapshot into the release it is named after.
function(_plasma_nm_detect_version library out_version out_origin)
    set(${out_version} "" PARENT_SCOPE)
    set(${out_origin} "" PARENT_SCOPE)

    find_program(_pacman_executable pacman)
    if(_pacman_executable)
        execute_process(COMMAND "${_pacman_executable}" -Qoq "${library}"
                        OUTPUT_VARIABLE owner RESULT_VARIABLE failed
                        OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
        if(failed EQUAL 0 AND NOT owner STREQUAL "")
            string(REPLACE "\n" ";" owners "${owner}")
            list(GET owners 0 owner)
            execute_process(COMMAND "${_pacman_executable}" -Q "${owner}"
                            OUTPUT_VARIABLE queried RESULT_VARIABLE failed
                            OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
            if(failed EQUAL 0 AND queried MATCHES "^[^ ]+ +([^ ]+)")
                set(${out_version} "${CMAKE_MATCH_1}" PARENT_SCOPE)
                set(${out_origin} "pacman package ${owner}" PARENT_SCOPE)
                return()
            endif()
        endif()
    endif()

    find_program(_dpkg_query_executable dpkg-query)
    if(_dpkg_query_executable)
        execute_process(COMMAND "${_dpkg_query_executable}" -S "${library}"
                        OUTPUT_VARIABLE owner RESULT_VARIABLE failed
                        OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
        if(failed EQUAL 0 AND owner MATCHES "^([^:,]+)[:,]")
            set(owner "${CMAKE_MATCH_1}")
            execute_process(COMMAND "${_dpkg_query_executable}" -W "--showformat=\${Version}" "${owner}"
                            OUTPUT_VARIABLE queried RESULT_VARIABLE failed
                            OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
            if(failed EQUAL 0 AND NOT queried STREQUAL "")
                set(${out_version} "${queried}" PARENT_SCOPE)
                set(${out_origin} "dpkg package ${owner}" PARENT_SCOPE)
                return()
            endif()
        endif()
    endif()

    find_program(_rpm_executable rpm)
    if(_rpm_executable)
        execute_process(COMMAND "${_rpm_executable}" -qf "--queryformat=%{NAME} %{VERSION}" "${library}"
                        OUTPUT_VARIABLE queried RESULT_VARIABLE failed
                        OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
        if(failed EQUAL 0 AND queried MATCHES "^([^ ]+) +([^ ]+)")
            set(${out_version} "${CMAKE_MATCH_2}" PARENT_SCOPE)
            set(${out_origin} "rpm package ${CMAKE_MATCH_1}" PARENT_SCOPE)
            return()
        endif()
    endif()
endfunction()

if(NOT PLASMA_NM_HOST_VERSION STREQUAL "")
    set(_plasma_nm_host_raw "${PLASMA_NM_HOST_VERSION}")
    set(_plasma_nm_host_origin "asserted with -DPLASMA_NM_HOST_VERSION")
else()
    _plasma_nm_detect_version("${PLASMA_NM_EDITOR_LIBRARY}" _plasma_nm_host_raw _plasma_nm_host_origin)
endif()
plasma_nm_upstream_version("${_plasma_nm_host_raw}" _plasma_nm_host_version)

# The comparison is exact rather than VERSION_EQUAL: 6.7.5 and 6.7.5.0 are the
# same number and not the same release, and nothing about this library's ABI
# follows from one version being newer than another.
if(_plasma_nm_host_raw STREQUAL "")
    string(CONCAT _plasma_nm_abi_complaint
        "The installed plasma-nm's version could not be determined: no package manager here owns "
        "${PLASMA_NM_EDITOR_LIBRARY}. Pass -DPLASMA_NM_HOST_VERSION=${PLASMA_NM_PIN_VERSION} once you "
        "have established that it really is ${PLASMA_NM_PIN_VERSION}.")
elseif(_plasma_nm_host_version STREQUAL "")
    string(CONCAT _plasma_nm_abi_complaint
        "The installed plasma-nm is version ${_plasma_nm_host_raw} (${_plasma_nm_host_origin}), which is "
        "not a plain upstream release: a prerelease, a snapshot or a patched rebuild is not the "
        "${PLASMA_NM_PIN_VERSION} these headers came from, whatever it is named after. Its editor library "
        "has no versioned ABI, so a module built against the wrong declarations crashes the connection "
        "editor rather than failing to load.")
elseif(NOT _plasma_nm_host_version STREQUAL PLASMA_NM_PIN_VERSION)
    string(CONCAT _plasma_nm_abi_complaint
        "The installed plasma-nm is ${_plasma_nm_host_version} (${_plasma_nm_host_origin}, package version "
        "${_plasma_nm_host_raw}) but this module is pinned to ${PLASMA_NM_PIN_VERSION}. plasma-nm's editor "
        "library has no versioned ABI, so loading a module built against different headers crashes the "
        "connection editor rather than failing to load. Build against a matching plasma-nm, or re-pin "
        "this module to ${_plasma_nm_host_version} and re-verify it.")
else()
    set(_plasma_nm_abi_complaint "")
    message(STATUS "Installed plasma-nm: ${_plasma_nm_host_version} (${_plasma_nm_host_origin}, "
                   "package version ${_plasma_nm_host_raw}) -- matches the pin")
endif()

if(NOT _plasma_nm_abi_complaint STREQUAL "")
    if(PLASMA_NM_ALLOW_ABI_MISMATCH)
        message(WARNING "${_plasma_nm_abi_complaint}\nBuilding anyway: PLASMA_NM_ALLOW_ABI_MISMATCH is on. "
                        "Do not ship the result.")
    else()
        message(FATAL_ERROR "${_plasma_nm_abi_complaint}\nSet -DPLASMA_NM_ALLOW_ABI_MISMATCH=ON to build "
                            "anyway; the result is not fit to ship.")
    endif()
endif()

set(PLASMA_NM_HOST_VERSION_RESOLVED "${_plasma_nm_host_version}")
set(PLASMA_NM_HOST_PACKAGE_VERSION "${_plasma_nm_host_raw}")
set(PLASMA_NM_HOST_VERSION_ORIGIN "${_plasma_nm_host_origin}")

add_library(PlasmaNm::Editor UNKNOWN IMPORTED)
set_target_properties(PlasmaNm::Editor PROPERTIES
    IMPORTED_LOCATION "${PLASMA_NM_EDITOR_LIBRARY}"
    INTERFACE_INCLUDE_DIRECTORIES "${_plasma_nm_include}"
    # What the four headers themselves need in order to be compiled: plasma-nm
    # links these PUBLIC for the same reason -- SettingWidget includes
    # KAcceleratorManager, VpnUiPlugin includes KPluginFactory and
    # NetworkManagerQt, and both derive from QWidget or QObject. The library's
    # own remaining dependencies are recorded in the shared object and need no
    # repeating here.
    INTERFACE_LINK_LIBRARIES "KF6::CoreAddons;KF6::NetworkManagerQt;KF6::WidgetsAddons;Qt::Widgets")
